### ISSUE TITLE
Where is the ZIP file?

### ISSUE THREAD

**Issue by nstrelow** [3dcitydb/3dcitydb-qgis-explorer#2]
Hey folks of the awesome 3dcitydb project.

Currently trying to use qgis to visualize and found this repo.

Where can I find the plugin in the .zip format that is talked about in the Readme? Thanks

I think @steffiarg in #1 tried to download the zip of the master branch of this repository.

**Comment by steffiarg** [comment]
Hola, yo lo descargue desde la pantalla principal "Code", la opcion "code" dentro del cuadro de color verde.
Si te llaga a funcionar el plugins avisame, yo no lo pude hacer andar.

Saludos

**Comment by nstrelow** [comment]
I sadly do not speak spanish, but from Google Translate I can hopefully get the meaning.

The ZIP you downloaded is not a plugin. It just contains every file in this project, which is: .gitignore, README.md, LICENSE

Google Translate
El ZIP que descargó no es un complemento. Solo contiene todos los archivos de este proyecto, que son: .gitignore, README.md, LICENSE

**Comment by steffiarg** [comment]
Hola! ahhh con razon! Entonces no sé donde esta el ZIP. Disculpa!

**Comment by sebastianfrey** [comment]
@nstrelow I have a message from one of the maintainers @lucacasagrande for you, since he has currently no access to GitHub.

He says:

"The plan is to publish the plugin in the offical qgis repository until mid-september. He also points out, that he is sorry for the fact, that the "Install from ZIP" does not work as described in the README."

**Comment by nstrelow** [comment]
@sebastianfrey and @lucacasagrande Thank you both so much. Really kind of you to take the time to answer this.

All the best and looking forward to seeing how the plugin works :)

**Comment by cikke** [comment]
2021.1.7

**Comment by cikke** [comment]
Hey folks of the awesome 3dcitydb project.

Currently trying to use qgis to visualize and found this repo.

Where can I find the plugin in the .zip format that is talked about in the Readme? Thanks

**Comment by nytschgeusen** [comment]
@clausnagel:  it would be great if you could upload the mentioned zip file for the 3dcitydb-qgis-explorer on GitHub in near future that we can test the plugin in QGIS :-)

**Comment by dokgeppo** [comment]
Sorry for taking so much time. I will publish the Code in the next days.

**Comment by nytschgeusen** [comment]
Thanks, that are great news 👍👍👍  I will give you feedback how your 3dcitydb-qgis-explorer plugin will work in combination with our QGIS plugin open eQuarter (https://plugins.qgis.org/plugins/mole/)

**Comment by yaozhihang** [comment]
I'm also looking forward to test this QGIS plugin 😄

**Comment by nytschgeusen** [comment]
@dokgeppo: can you give us a time horizon when the code will be published ?

**Comment by dokgeppo** [comment]
> @dokgeppo: can you give us a time horizon when the code will be published ?

It should be online at the end of this week. Sorry once again!

**Comment by nytschgeusen** [comment]
@dokgeppo: Great 👍

**Comment by dokgeppo** [comment]
First release is online. Please test :)
